name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:
#     - uses: actions/checkout@v2
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag jdposa/hugo_backend:$(date +%s)
    - name: Checkout code
      uses: actions/checkout@v2

    # setup Docker buld action
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build image and push to Docker Hub and GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: jdposa/hugo_backend:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
